### ISSUE TITLE
VSCodeの拡張機能などを永続化する

### ISSUE THREAD

**Issue by silverag-corgi** [silverag-corgi/dev-container-python#9]
## 概要

- VSCodeの拡張機能などを永続化する
  - `~/.vscode-server`

## ToDoリスト

- [x] Issueの作成・確認
- [x] 実現方法の調査
- [x] 対応方針の検討
- [x] 実装
- [x] PRの作成
- [x] テストケースの作成
- [x] テストの実施
- [x] 大元のブランチへのマージ

**Comment by silverag-corgi** [comment]
## 実現方法の調査

- docker compose docs volumes - Google 検索
  - https://www.google.com/search?q=docker+compose+docs+volumes
- Compose file version 3 reference | Docker Docs
  - https://docs.docker.com/compose/compose-file/compose-file-v3/

**Comment by silverag-corgi** [comment]
## ビルドエラー

### ログ

```log
[2023-10-18T15:32:13.092Z] Start: Run in container: test ! -f '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2023-10-18T15:32:13.096Z] 
[2023-10-18T15:32:13.096Z] mkdir: ディレクトリ `/home/vscode/.vscode-server/data' を作成できません: 許可がありません
[2023-10-18T15:32:13.096Z] Exit code 1
[2023-10-18T15:32:13.096Z] Stop (4 ms): Run in container: test ! -f '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' && set -o noclobber && mkdir -p '/home/vscode/.vscode-server/data/Machine' && { > '/home/vscode/.vscode-server/data/Machine/.writeMachineSettingsMarker' ; } 2> /dev/null
[2023-10-18T15:32:13.096Z] Start: Run in container: cat /home/vscode/.vscode-server/data/Machine/settings.json
[2023-10-18T15:32:13.098Z] 
[2023-10-18T15:32:13.099Z] cat: /home/vscode/.vscode-server/data/Machine/settings.json: そのようなファイルやディレクトリはありません
[2023-10-18T15:32:13.099Z] Exit code 1
[2023-10-18T15:32:13.099Z] Stop (3 ms): Run in container: cat /home/vscode/.vscode-server/data/Machine/settings.json
[2023-10-18T15:32:13.099Z] Start: Run in container: test -d /home/vscode/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc
[2023-10-18T15:32:13.101Z] 
[2023-10-18T15:32:13.101Z] 
[2023-10-18T15:32:13.102Z] Exit code 1
[2023-10-18T15:32:13.102Z] Stop (3 ms): Run in container: test -d /home/vscode/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc
[2023-10-18T15:32:13.102Z] Start: Run in container: test -d /vscode/vscode-server/bin/linux-x64/f1b07bd25dfad64b0167beb15359ae573aecd2cc
[2023-10-18T15:32:13.103Z] 
[2023-10-18T15:32:13.103Z] 
[2023-10-18T15:32:13.103Z] Stop (1 ms): Run in container: test -d /vscode/vscode-server/bin/linux-x64/f1b07bd25dfad64b0167beb15359ae573aecd2cc
[2023-10-18T15:32:13.104Z] Start: Run in container: mkdir -p '/home/vscode/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/f1b07bd25dfad64b0167beb15359ae573aecd2cc' '/home/vscode/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc'
[2023-10-18T15:32:13.106Z] 
[2023-10-18T15:32:13.106Z] mkdir: ディレクトリ `/home/vscode/.vscode-server/bin' を作成できません: 許可がありません
[2023-10-18T15:32:13.106Z] Exit code 1
[2023-10-18T15:32:13.106Z] Stop (2 ms): Run in container: mkdir -p '/home/vscode/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/f1b07bd25dfad64b0167beb15359ae573aecd2cc' '/home/vscode/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc'
[2023-10-18T15:32:13.109Z] Command in container failed: mkdir -p '/home/vscode/.vscode-server/bin' && ln -snf '/vscode/vscode-server/bin/linux-x64/f1b07bd25dfad64b0167beb15359ae573aecd2cc' '/home/vscode/.vscode-server/bin/f1b07bd25dfad64b0167beb15359ae573aecd2cc'
[2023-10-18T15:32:13.109Z] mkdir: ディレクトリ `/home/vscode/.vscode-server/bin' を作成できません: 許可がありません
[2023-10-18T15:32:13.109Z] Exit code 1
[2023-10-18T15:33:25.525Z] Start: Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\silverag\workspace\Git\python\dev-container-python
[2023-10-18T15:33:25.681Z] Stop (156 ms): Run: wsl -d Ubuntu-22.04 -e wslpath -u \\wsl.localhost\Ubuntu-22.04\home\silverag\workspace\Git\python\dev-container-python
[2023-10-18T15:33:25.850Z] Error opening dev container configurations: CodeExpectedError: ENOPRO: リソース 'vscode-remote://dev-container%2B7b22686f737450617468223a225c5c5c5c77736c2e6c6f63616c686f73745c5c5562756e74752d32322e30345c5c686f6d655c5c73696c76657261675c5c776f726b73706163655c5c4769745c5c707974686f6e5c5c6465762d636f6e7461696e65722d707974686f6e222c226c6f63616c446f636b6572223a66616c73652c22636f6e66696746696c65223a7b22246d6964223a312c2270617468223a222f686f6d652f73696c76657261672f776f726b73706163652f4769742f707974686f6e2f6465762d636f6e7461696e65722d707974686f6e2f2e646576636f6e7461696e65722f646576636f6e7461696e65722e6a736f6e222c22736368656d65223a227673636f64652d66696c65486f7374227d7d/home/vscode' のファイル システム プロバイダーが見つかりません
    at r.j (vscode-file://vscode-app/c:/Users/silverag/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:11397)
    at async r.exists (vscode-file://vscode-app/c:/Users/silverag/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:645:13603)
    at async Promise.all (index 0)
    at async vscode-file://vscode-app/c:/Users/silverag/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1861:2796
```

### 解決策

- `Dockerfile`にてログインユーザで`/home/vscode/.vscode-server`を作成しておく

**Comment by silverag-corgi** [comment]
## 課題

拡張機能を永続化することは実現できた。
しかし、`devcontainers.json`に設定や拡張機能を追記して、再ビルドしても反映されない。

## 実現方法の調査

- vscode 拡張機能 volume mount - Google 検索
  - https://www.google.com/search?q=vscode+拡張機能+volume+mount
- DockerとVS Code Remote Containersを用いたフロントエンド開発環境構築
  - https://zenn.dev/leftletter/articles/0969dcef061ff8#ファイルの個別説明
    > 再ビルドのたびに拡張機能のインストールを行うのを防ぎますが、
    > `devcontainers.json`に新たにインストールしたい拡張機能を追加しても反映されないため、
    > その際はボリュームを削除する必要があります。

**Comment by silverag-corgi** [comment]
設定や拡張機能を反映させるためにはボリュームを削除する必要があるとのことだが、
それでは永続化した意味がないため、リバートする。
